services:
  postgres:
    container_name: postgres_container
    image: postgres:17
    environment:
      POSTGRES_DB: plant-orders
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
        - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8

    environment:
      PGADMIN_DEFAULT_EMAIL: worcho95@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
          - postgres
    restart: unless-stopped
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:


